---
name: CIRCL
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
jobs:
  amd64_job:
    name: Go-${{matrix.GOVER}}/amd64
    if: 1==0
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        GOVER: ['1.14', '1.13', '1.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linting
        uses: golangci/golangci-lint-action@v1
        with:
          version: v1.25
          args: --config=./.etc/golangci.yml ./...
      - name: Setup Go-${{ matrix.GOVER }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.GOVER }}
      - name: Verifying Code
        run: |
         go generate -v ./... && test -z "$(git status --porcelain)"
         go vet ./...
      - name: Building
        run: go build -v ./...
      - name: Testing
        run: go test -v ./...
  s390x_job:
    name: Go-1.14/s390x
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Enabling Docker Experimental
        run: |
          echo $'{\n\t"experimental": true\n}' | sudo tee /etc/docker/daemon.json
          sudo service docker restart
      - name: Pulling Images
        run: |
          docker pull -q multiarch/qemu-user-static
          docker pull -q multiarch/fedora:29-s390x
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
      - name: Testing
        uses: ./.github/actions/fedora-s390x
  coverage_amd64_job:
    needs: [amd64_job]
    if: github.event_name == 'push'
    runs-on: ubuntu-18.04
    name: amd64/coverage
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - name: Produce Coverage
        run: go test -race -coverprofile=./coverage.txt -covermode=atomic ./...
      - name: Upload Codecov
        uses: codecov/codecov-action@v1
        with:
          file: ./coverage.txt
