name: CIRCL
on: 
  push:
    branches: 
      - master
  pull_request:
    branches: 
      - master
jobs:          
  test:
    name: Testing in Go-${{matrix.GOVER}}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        GOVER: ['1.12', '1.13', '1.14']
    steps:
      - name: Testing
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.GOVER }} 
      - run: |
          go generate - ./... && test -z "$(git status --porcelain)"
      - uses: actions-contrib/golangci-lint@v1
        with:
          golangci_lint_version: v1.18.0
          args: run --config .etc/golangci.yml ./...
      - run: |
          go vet ./...
          go test -v ./...
