name: CIRCL
on:
  push:
    branches:
      - master
      - enabling-ci
  pull_request:
    branches:
      - master
jobs:
  amd64_job:
    name: amd64/Go-${{matrix.GOVER}}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        GOVER: ['1.12', '1.13', '1.14']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Linting
        uses: ./.github/actions/golangci-lint
        with:
          args: run --config=.etc/golangci.yml ./...
      - name: Setup Go-${{ matrix.GOVER }}
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.GOVER }}
      - name: Verifying Code
        run: |
         go generate -v ./... && test -z "$(git status --porcelain)"
         go vet ./...
      - name: Building
        run: go build -v ./...
      - name: Testing
        run: go test -v ./...
  arm64_job:
    runs-on: ubuntu-18.04
    name: arm64/Go-1.14
    env:
        GOVER: 1.14
        SHA256: sha256:944405641f9fb0f322be1dfc4685b916df2de3df54525cf80822f8a0529f636f
    steps:
      - uses: actions/checkout@v2
      - name: Pulling Images
        run: |
          docker pull -q multiarch/qemu-user-static
          docker pull -q arm64v8/golang@$SHA256
      - name: Testing
        run: |
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
          docker run --rm -v `pwd`:`pwd` -w `pwd` arm64v8/golang@$SHA256 go test -v ./...
