name: CIRCL
on:
  push:
    branches:
      - master
      - enabling-ci
  pull_request:
    branches:
      - master
jobs:
  test:
    name: Testing in Go-${{matrix.GOVER}}
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        GOVER: ['1.12']
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go-${{matrix.GOVER}}
        uses: actions/setup-go@v2-beta
        with:
          go-version: ${{ matrix.GOVER }}
      - name: Go
        run: |
          go env GOPATH
          go env GOROOT
          go version
          echo $GITHUB_WORKSPACE
      - name: Verifying Code
        run: |
         go generate - ./... && test -z "$(git status --porcelain)"
         go vet ./...
      - name: Building
        run: |
          go build -v ./...
      - name: Testing
        run: |
          go test -v ./...
      - name: Linting
        uses: actions-contrib/golangci-lint@v1
        with:
          golangci_lint_version: v1.18.0
          working-directory: $GITHUB_WORKSPACE
          args: run --config=.etc/golangci.yml ./...
